const PLUS = "PLUS";
const MINUS = "MINUS";
const CHANGE_THEME = "CHANGE_THEME";

const DISABLE_BUTTONS = "DISABLE_BUTTONS";
const ENABLE_BUTTONS = "ENABLE_BUTTONS";

export { PLUS, MINUS, CHANGE_THEME,DISABLE_BUTTONS,ENABLE_BUTTONS };
